baseurl = "https://aadyasharma.in"
googleAnalytics = ""
languageCode = "en-us"
paginate = 6
summaryLength = "10"
theme = "parsa-hugo"
title = "Aadya Sharma"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Admin"
url = "/admin"
weight = 4
[[menu.main]]
name = "Homepage "
parent = "Homepage"
url = "homepage/home"
weight = "1"
[[menu.main]]
name = "About"
url = "about"
weight = 2
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
address = ""
author = "Aadya Sharma"
author_image = "images/banner-img.png"
bio = "I am an avid writer and an aspiring photographer and journalist, currently studying Journalism and Mass Communication at GD Goenka University."
contact_form_action = "#"
copyright = "&copy; 2022 Aadya Sharma "
description = "I am an avid writer and an aspiring photographer and journalist, currently studying Journalism and Mass Communication at GD Goenka University."
email = "aadyasharma2905@gmail.com"
home = "Home"
layout = "1"
logo = "images/logo.png"
mobile = ""
preloader = true
search = true
[params.cookies]
enable = true
expire_days = 2
[params.instafeed]
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"
enable = false
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/aadyasharma29"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/in/aadya-sharma-638208221/"
